data(GermanCredit)
summary(GermanCredit)
str(GermanCredit)
nrow(GermanCredit)
GC_sample <- strata(GermanCredit,stratanames="credit_risk",size=rep(100,2),method="srswor")
GC_train <- getdata(GermanCredit, GC_sample$ID_unit)
GC_test <- getdata(GermanCredit, -GC_sample$ID_unit)
model=svm(credit_risk~.,data=GC_train)
pred=predict(model,GC_test[-21])	
table(pred,GC_test$credit_risk)	
